version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8020
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8020:8020"
    environment:
      - DEBUG=1
      - DB_NAME=ecommerce_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,49.12.69.85,ecm-fnf.vercel.app,ecm-fnf.netlify.app
      - CORS_ALLOWED_ORIGINS=http://localhost:3434,http://127.0.0.1:3434,https://ecm-fnf.netlify.app,https://ecm-fnf.vercel.app/
      - CSRF_TRUSTED_ORIGINS=http://localhost:3434,http://127.0.0.1:3434,https://ecm-fnf.netlify.app,https://ecm-fnf.vercel.app/
      - SECURE_SSL_REDIRECT=False
    depends_on:
      - db
    entrypoint: /docker-entrypoint.dev.sh

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5443:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume:
